### ISSUE TITLE
Working with files

### ISSUE THREAD

**Issue by k-forghani** [shadmehr-salehi/Python-Lectures#4]
Hello,
Please consider adding a section on how to work with files in Python, as it is essential in most tasks.
I mention some related subtopics here:

- Reading and Writing Plain Files
- Working with `pickle`
- Working with `JSON` and `CSV` files via Native Python
- Listing Files using `glob`

**Comment by shadmehr-salehi** [comment]
I won't add the third suggestion as it's already mentioned in the **pandas** section, and working with JSON files is not necessary to mention in notebooks.

**Comment by k-forghani** [comment]
In many situations, due to simplicity, using native `json` package of Python is preferred over `Pandas`. One of these situations is storing data without any need to statistical computations. When developing an API, data may be transferred in `JSON` format which using `Pandas` is not necessary.
